---
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: feat
      include: scope
    allow:
      - dependency-name: '@seamapi/types'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
    groups:
      seam:
        dependency-type: development
        patterns:
          - '@seamapi/types'
        update-types:
          - patch
          - minor
