---
root: ./docs/
​structure:
  readme: README.md
  summary: SUMMARY.md
redirects:
  latest/quickstart/get-api-key: latest/quickstart.md
  quickstart/get-api-key: quickstart.md
  quickstart/installation: quickstart.md
  quickstart/authentication: quickstart.md
  quickstart/connect-a-device: quickstart.md
  quickstart/your-first-device-api-call: quickstart.md
  quickstart/going-live: quickstart.md
  going-live: go-live.md
  core-concepts/workspaces/api-keys: core-concepts/authentication/api-keys.md
  core-concepts/workspaces/personal-access-tokens: core-concepts/authentication/personal-access-tokens.md
  core-concepts/workspaces/client-session-tokens: core-concepts/authentication/client-session-tokens/README.md
  core-concepts/workspaces/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend: core-concepts/authentication/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend.md
  products/access-systems/user-management: capability-guides/access-systems/user-management/README.md
  capability-guides/access-systems/managing-credentials: capability-guides/access-systems/managing-credentials/README.md
  capability-guides/access-systems/assigning-credentials-to-users: capability-guides/access-systems/managing-credentials/assigning-credentials-to-users.md
  products/access-systems/suspending-and-unsuspending-users: capability-guides/access-systems/user-management/suspending-and-unsuspending-users.md
  products/seam-bridge-in-development: capability-guides/seam-bridge.md
  core-concepts/connect-webviews: core-concepts/connect-webviews/README.md
  device-guides/4suites-locks: device-and-system-integration-guides/4suites-locks/README.md
  device-guides/assa-abloy-visionline-access-control-system-in-development: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/README.md
  device-guides/assa-abloy-visionline-access-control-system-in-development/credential-types: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/credential-types.md
  device-and-system-integration-guides/assa-abloy-visionline-access-control-system-in-development/visionline-credential-metadata: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/visionline-credential-metadata.md
  device-guides/assa-abloy-visionline-access-control-system-in-development/common-use-cases: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/common-use-cases.md
  device-and-system-integration-guides/assa-abloy-visionline-access-control-system-in-development/special-requirements-for-android-mobile-access-sdk-development: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/special-requirements-for-android-mobile-access-sdk-development.md
  device-and-system-integration-guides/assa-abloy-visionline-access-control-system-in-development/special-requirements-for-ios-mobile-access-sdk-development: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/special-requirements-for-ios-mobile-access-sdk-development.md
  capability-guides/access-systems/understanding-acs-differences: capability-guides/access-systems/understanding-access-control-system-differences.md
  device-guides/get-started-with-schlage-locks: device-and-system-integration-guides/schlage-locks/get-started-with-schlage-locks.md
  api-clients/access-codes/convert-an-unmanaged-access-code: docs/api-clients/access_codes/unmanaged/convert_to_managed.md
  api-clients/access-codes/create-an-access-code: docs/api-clients/access_codes/create.md
  api-clients/access-codes/create-many-access-codes: docs/api-clients/access_codes/create_multiple.md
  api-clients/access-codes/delete-an-access-code: docs/api-clients/access_codes/delete.md
  api-clients/access-codes/delete-an-unmanaged-access-code: docs/api-clients/access_codes/unmanaged/delete.md
  api-clients/access-codes/get-an-access-code: docs/api-clients/access_codes/get.md
  api-clients/access-codes/get-an-unmanaged-access-code: docs/api-clients/access_codes/unmanaged/get.md
  api-clients/access-codes/list-access-codes: docs/api-clients/access_codes/list.md
  api-clients/access-codes/list-unmanaged-access-codes: docs/api-clients/access_codes/unmanaged/list.md
  api-clients/access-codes/pull-backup-access-code: docs/api-clients/access_codes/pull_backup_access_code.md
  api-clients/access-codes/update-an-access-code: docs/api-clients/access_codes/update.md
  api-clients/access-codes: docs/api-clients/access_codes/README.md
  api-clients/access-control-systems/access-groups/add-user-to-access-group: docs/api-clients/acs/access_groups/add_user.md
  api-clients/access-control-systems/access-groups/get-access-group: docs/api-clients/acs/access_groups/get.md
  api-clients/access-control-systems/access-groups/list-access-groups: docs/api-clients/acs/access_groups/list.md
  api-clients/access-control-systems/access-groups/list-users-in-access-group: docs/api-clients/acs/access_groups/list_users.md
  api-clients/access-control-systems/access-groups/remove-user-from-access-group: docs/api-clients/acs/access_groups/remove_user.md
  api-clients/access-control-systems/access-groups: docs/api-clients/acs/access_groups/README.md
  api-clients/access-control-systems/credentials/assign-a-credential-to-a-user: docs/api-clients/acs/credentials/assign.md
  api-clients/access-control-systems/credentials/create-credential-for-user: docs/api-clients/acs/credentials/create.md
  api-clients/access-control-systems/credentials/delete-credential: docs/api-clients/acs/credentials/delete.md
  api-clients/access-control-systems/credentials/get-credential: docs/api-clients/acs/credentials/get.md
  api-clients/access-control-systems/credentials/list-accessible-entrances: docs/api-clients/acs/credentials/list_accessible_entrances.md
  api-clients/access-control-systems/credentials/list-credentials: docs/api-clients/acs/credentials/list.md
  api-clients/access-control-systems/credentials/unassign-a-credential-from-a-user: docs/api-clients/acs/credentials/unassign.md
  api-clients/access-control-systems/credentials/update-a-credential: docs/api-clients/acs/credentials/update.md
  api-clients/access-control-systems/credentials: docs/api-clients/acs/credentials/README.md
  api-clients/access-control-systems/entrances/get-an-entrance: docs/api-clients/acs/entrances/get.md
  api-clients/access-control-systems/entrances/list-credentials-with-access-to-an-entrance: docs/api-clients/acs/entrances/list_credentials_with_access.md
  api-clients/access-control-systems/entrances/list-entrances: docs/api-clients/acs/entrances/list.md
  api-clients/access-control-systems/entrances: docs/api-clients/acs/entrances/README.md
  api-clients/access-control-systems/systems/get-system: docs/api-clients/acs/systems/get.md
  api-clients/access-control-systems/systems/list-compatible-credential-manager-acs-systems: docs/api-clients/acs/systems/list_compatible_credential_manager_acs_systems.md
  api-clients/access-control-systems/systems/list-systems: docs/api-clients/acs/systems/list.md
  api-clients/access-control-systems/systems: docs/api-clients/acs/systems/README.md
  api-clients/access-control-systems/users/add-user-to-access-group: docs/api-clients/acs/users/add_to_access_group.md
  api-clients/access-control-systems/users/create-user: docs/api-clients/acs/users/create.md
  api-clients/access-control-systems/users/delete-user: docs/api-clients/acs/users/delete.md
  api-clients/access-control-systems/users/get-user: docs/api-clients/acs/users/get.md
  api-clients/access-control-systems/users/list-users: docs/api-clients/acs/users/list.md
  api-clients/access-control-systems/users/remove-user-from-access-group: docs/api-clients/acs/users/remove_from_access_group.md
  api-clients/access-control-systems/users/suspend-a-user: docs/api-clients/acs/users/suspend.md
  api-clients/access-control-systems/users/unsuspend-a-user: docs/api-clients/acs/users/unsuspend.md
  api-clients/access-control-systems/users/update-user: docs/api-clients/acs/users/update.md
  api-clients/access-control-systems/users: docs/api-clients/acs/users/README.md
  api-clients/access-control-systems: docs/api-clients/acs/README.md
  api-clients/action-attempt/get-action-attempt: docs/api-clients/action_attempts/get.md
  api-clients/action-attempt: docs/api-clients/action_attempts/README.md
  api-clients/client-sessions/create-a-client-session: docs/api-clients/client_sessions/create.md
  api-clients/client-sessions/delete-a-client-session: docs/api-clients/client_sessions/delete.md
  api-clients/client-sessions/get-a-client-session: docs/api-clients/client_sessions/get.md
  api-clients/client-sessions/get-or-create-a-client-session: docs/api-clients/client_sessions/get_or_create.md
  api-clients/client-sessions/grant-access-to-a-client-session: docs/api-clients/client_sessions/grant_access.md
  api-clients/client-sessions/list-client-sessions: docs/api-clients/client_sessions/list.md
  api-clients/client-sessions: docs/api-clients/client_sessions/README.md
  api-clients/connect-webviews/create-a-connect-webview: docs/api-clients/connect_webviews/create.md
  api-clients/connect-webviews/delete-a-connect-webview: docs/api-clients/connect_webviews/delete.md
  api-clients/connect-webviews/get-a-connect-webview: docs/api-clients/connect_webviews/get.md
  api-clients/connect-webviews/list-connect-webviews: docs/api-clients/connect_webviews/list.md
  api-clients/connect-webviews: docs/api-clients/connect_webviews/README.md
  api-clients/connected-accounts/delete-a-connected-account: docs/api-clients/connected_accounts/delete.md
  api-clients/connected-accounts/get-a-connected-account: docs/api-clients/connected_accounts/get.md
  api-clients/connected-accounts/list-connected-accounts: docs/api-clients/connected_accounts/list.md
  api-clients/connected-accounts/update-a-connected-account: docs/api-clients/connected_accounts/update.md
  api-clients/connected-accounts: docs/api-clients/connected_accounts/README.md
  api-clients/devices/delete-device: docs/api-clients/devices/delete.md
  api-clients/devices/get-device-1: docs/api-clients/devices/unmanaged/get.md
  api-clients/devices/get-device: docs/api-clients/devices/get.md
  api-clients/devices/list-device-providers: docs/api-clients/devices/list_device_providers.md
  api-clients/devices/list-devices: docs/api-clients/devices/list.md
  api-clients/devices/list-unmanaged-devices: docs/api-clients/devices/unmanaged/list.md
  api-clients/devices/update-device: docs/api-clients/devices/update.md
  api-clients/devices/update-unmanaged-device: docs/api-clients/devices/unmanaged/update.md
  api-clients/events/get-an-event: docs/api-clients/events/get.md
  api-clients/events/list-events: docs/api-clients/events/list.md
  api-clients/locks/get-lock: docs/api-clients/locks/get.md
  api-clients/locks/list-locks: docs/api-clients/locks/list.md
  api-clients/locks/lock-a-lock: docs/api-clients/locks/lock_door.md
  api-clients/locks/unlock-a-lock: docs/api-clients/locks/unlock_door.md
  api-clients/noise-sensors/create-noise-threshold: docs/api-clients/noise_sensors/noise_thresholds/create.md
  api-clients/noise-sensors/delete-noise-threshold: docs/api-clients/noise_sensors/noise_thresholds/delete.md
  api-clients/noise-sensors/list-noise-thresholds: docs/api-clients/noise_sensors/noise_thresholds/list.md
  api-clients/noise-sensors/update-noise-threshold: docs/api-clients/noise_sensors/noise_thresholds/update.md
  api-clients/noise-sensors: docs/api-clients/noise_sensors/README.md
  api-clients/thermostats/get-thermostat: docs/api-clients/thermostats/get.md
  api-clients/thermostats/list-thermostats: docs/api-clients/thermostats/list.md
  api-clients/thermostats/set-fan-mode: docs/api-clients/thermostats/set_fan_mode.md
  api-clients/thermostats/set-to-cool-mode: docs/api-clients/thermostats/cool.md
  api-clients/thermostats/set-to-heat-cool-auto-mode: docs/api-clients/thermostats/heat_cool.md
  api-clients/thermostats/set-to-heat-mode: docs/api-clients/thermostats/heat.md
  api-clients/thermostats/set-to-off-mode: docs/api-clients/thermostats/off.md
  api-clients/user-identities/add-an-acs-user-to-a-user-identity: docs/api-clients/user_identities/add_acs_user.md
  api-clients/user-identities/create-a-user-identity: docs/api-clients/user_identities/create.md
  api-clients/user-identities/delete-a-user-identity: docs/api-clients/user_identities/delete.md
  api-clients/user-identities/enrollment-automations/delete-an-enrollment-automation: docs/api-clients/user_identities/enrollment_automations/delete.md
  api-clients/user-identities/enrollment-automations/get-an-enrollment-automation: docs/api-clients/user_identities/enrollment_automations/get.md
  api-clients/user-identities/enrollment-automations/launch-an-enrollment-automation: docs/api-clients/user_identities/enrollment_automations/launch.md
  api-clients/user-identities/enrollment-automations/list-enrollment-automations: docs/api-clients/user_identities/enrollment_automations/list.md
  api-clients/user-identities/enrollment-automations: docs/api-clients/user_identities/enrollment_automations/README.md
  api-clients/user-identities/get-a-user-identity: docs/api-clients/user_identities/get.md
  api-clients/user-identities/grant-a-user-identity-access-to-a-device: docs/api-clients/user_identities/grant_access_to_device.md
  api-clients/user-identities/list-accessible-devices-for-a-user-identity: docs/api-clients/user_identities/list_accessible_devices.md
  api-clients/user-identities/list-acs-systems-associated-with-a-user-identity: docs/api-clients/user_identities/list_acs_systems.md
  api-clients/user-identities/list-acs-users-associated-with-a-user-identity: docs/api-clients/user_identities/list_acs_users.md
  api-clients/user-identities/list-user-identities: docs/api-clients/user_identities/list.md
  api-clients/user-identities/remove-an-acs-user-from-a-user-identity: docs/api-clients/user_identities/remove_acs_user.md
  api-clients/user-identities/revoke-access-to-a-device-from-a-user-identity: docs/api-clients/user_identities/revoke_access_to_device.md
  api-clients/user-identities: docs/api-clients/user_identities/README.md
  api-clients/workspaces/get-workspace: docs/api-clients/workspaces/get.md
  api-clients/workspaces/reset-workspace: docs/api-clients/workspaces/reset_sandbox.md
