---
root: ./docs/guides/
​structure:
  readme: README.md
  summary: SUMMARY.md
redirects:
  quickstart/get-api-key: quickstart.md
  quickstart/installation: quickstart.md
  quickstart/authentication: quickstart.md
  quickstart/connect-a-device: quickstart.md
  quickstart/your-first-device-api-call: quickstart.md
  quickstart/going-live: quickstart.md
  going-live: go-live.md
  core-concepts/workspaces/api-keys: core-concepts/authentication/api-keys.md
  core-concepts/workspaces/personal-access-tokens: core-concepts/authentication/personal-access-tokens.md
  core-concepts/workspaces/client-session-tokens: core-concepts/authentication/client-session-tokens/README.md
  core-concepts/workspaces/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend: core-concepts/authentication/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend.md
  products/access-systems/user-management: capability-guides/access-systems/user-management.md
  capability-guides/access-systems/managing-credentials: capability-guides/access-systems/managing-credentials.md
  capability-guides/access-systems/assigning-credentials-to-users: capability-guides/access-systems/managing-credentials/assigning-credentials-to-users.md
  products/access-systems/suspending-and-unsuspending-users: capability-guides/access-systems/user-management/suspending-and-unsuspending-users.md
  products/seam-bridge-in-development: capability-guides/seam-bridge.md
  core-concepts/connect-webviews: core-concepts/connect-webviews/README.md
  capability-guides/access-systems/understanding-acs-differences: capability-guides/access-systems/README.md
  capability-guides/thermostats/creating-and-managing-climate-schedules: capability-guides/thermostats/creating-and-managing-thermostat-schedules.md
  capability-guides/access-grants: use-cases/granting-access/README.md
  capability-guides/access-grants/access-grant-quick-start: use-cases/granting-access/access-grant-quick-start.md
  capability-guides/access-grants/creating-an-access-grant-using-entrances: use-cases/granting-access/creating-an-access-grant-using-entrances.md
  capability-guides/access-grants/creating-an-access-grant-using-spaces: use-cases/granting-access/creating-an-access-grant-using-spaces.md
  capability-guides/access-grants/delivering-access-methods: use-cases/granting-access/delivering-access-methods.md
  capability-guides/access-grants/reservation-access-grants: use-cases/granting-access/reservation-access-grants.md
  capability-guides/access-grants/retrieving-access-grants-and-access-methods: use-cases/granting-access/retrieving-access-grants-and-access-methods.md
  capability-guides/access-grants/updating-an-access-grant: use-cases/granting-access/updating-an-access-grant.md
  capability-guides/access-grants/revoking-an-access-method: use-cases/granting-access/revoking-an-access-method.md
  capability-guides/access-grants/deleting-an-access-grant: use-cases/granting-access/deleting-an-access-grant.md
