---
root: ./docs/guides/
​structure:
  readme: README.md
  summary: SUMMARY.md
redirects:
  quickstart/get-api-key: quickstart.md
  quickstart/installation: quickstart.md
  quickstart/authentication: quickstart.md
  quickstart/connect-a-device: quickstart.md
  quickstart/your-first-device-api-call: quickstart.md
  quickstart/going-live: quickstart.md
  going-live: go-live.md
  core-concepts/workspaces/api-keys: core-concepts/authentication/api-keys.md
  core-concepts/workspaces/personal-access-tokens: core-concepts/authentication/personal-access-tokens.md
  core-concepts/workspaces/client-session-tokens: core-concepts/authentication/client-session-tokens/README.md
  core-concepts/workspaces/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend: core-concepts/authentication/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend.md
  products/access-systems/user-management: low-level-apis/access-systems/user-management.md
  capability-guides/access-systems/managing-credentials: low-level-apis/access-systems/managing-credentials.md
  capability-guides/access-systems/assigning-credentials-to-users: low-level-apis/access-systems/managing-credentials/assigning-credentials-to-users.md
  products/access-systems/suspending-and-unsuspending-users: low-level-apis/access-systems/user-management/suspending-and-unsuspending-users.md
  products/seam-bridge-in-development: capability-guides/seam-bridge.md
  core-concepts/connect-webviews: core-concepts/connect-webviews/README.md
  capability-guides/access-systems/understanding-acs-differences: low-level-apis/access-systems/README.md
  capability-guides/thermostats/creating-and-managing-climate-schedules: capability-guides/thermostats/creating-and-managing-thermostat-schedules.md
  capability-guides/access-grants: use-cases/granting-access/README.md
  capability-guides/access-grants/access-grant-quick-start: use-cases/granting-access/access-grant-quick-start.md
  capability-guides/access-grants/creating-an-access-grant-using-entrances: use-cases/granting-access/creating-an-access-grant-using-entrances.md
  capability-guides/access-grants/creating-an-access-grant-using-spaces: use-cases/granting-access/creating-an-access-grant-using-spaces.md
  capability-guides/access-grants/delivering-access-methods: use-cases/granting-access/delivering-access-methods.md
  capability-guides/access-grants/reservation-access-grants: use-cases/granting-access/reservation-access-grants.md
  capability-guides/access-grants/retrieving-access-grants-and-access-methods: use-cases/granting-access/retrieving-access-grants-and-access-methods.md
  capability-guides/access-grants/updating-an-access-grant: use-cases/granting-access/updating-an-access-grant.md
  capability-guides/access-grants/revoking-an-access-method: use-cases/granting-access/revoking-an-access-method.md
  capability-guides/access-grants/deleting-an-access-grant: use-cases/granting-access/deleting-an-access-grant.md
  capability-guides/access-systems/acs-quick-starts/encodable-key-card-quick-start: low-level-apis/access-systems/acs-quick-starts/encodable-key-card-quick-start.md
  capability-guides/access-systems/acs-quick-starts/mobile-key-quick-start: low-level-apis/access-systems/acs-quick-starts/mobile-key-quick-start.md
  capability-guides/access-systems/acs-quick-starts/pin-code-quick-start: low-level-apis/access-systems/acs-quick-starts/pin-code-quick-start.md
  capability-guides/access-systems/acs-quick-starts: low-level-apis/access-systems/acs-quick-starts/README.md
  capability-guides/access-systems/connect-an-acs-to-seam: low-level-apis/access-systems/connect-an-acs-to-seam/README.md
  capability-guides/access-systems/managing-credentials/assigning-credentials-to-users: low-level-apis/access-systems/managing-credentials/assigning-credentials-to-users.md
  capability-guides/access-systems/managing-credentials/listing-credentials-and-associated-entrances: low-level-apis/access-systems/managing-credentials/listing-credentials-and-associated-entrances.md
  capability-guides/access-systems/retrieving-entrance-details: low-level-apis/access-systems/retrieving-entrance-details.md
  capability-guides/access-systems/troubleshooting-your-access-control-system: low-level-apis/access-systems/troubleshooting-your-access-control-system.md
  capability-guides/access-systems/user-management/assigning-users-to-access-groups: low-level-apis/access-systems/user-management/assigning-users-to-access-groups.md
  capability-guides/access-systems/user-management/suspending-and-unsuspending-users: low-level-apis/access-systems/user-management/suspending-and-unsuspending-users.md
  capability-guides/access-systems/working-with-card-encoders-and-scanners/creating-and-encoding-card-access-methods: low-level-apis/access-systems/working-with-card-encoders-and-scanners/creating-and-encoding-card-access-methods.md
  capability-guides/access-systems/working-with-card-encoders-and-scanners/scanning-encoded-cards: low-level-apis/access-systems/working-with-card-encoders-and-scanners/scanning-encoded-cards.md
  capability-guides/smart-locks/access-codes/access-code-requirements-for-door-locks: low-level-apis/smart-locks/access-codes/access-code-requirements-for-door-locks.md
  capability-guides/smart-locks/access-codes/accommodating-manufacturer-mobile-apps: low-level-apis/smart-locks/access-codes/accommodating-manufacturer-mobile-apps.md
  capability-guides/smart-locks/access-codes/backup-access-codes: low-level-apis/smart-locks/access-codes/backup-access-codes.md
  capability-guides/smart-locks/access-codes/creating-access-codes/understanding-code-constraints: low-level-apis/smart-locks/access-codes/creating-access-codes/understanding-code-constraints.md
  capability-guides/smart-locks/access-codes/creating-and-updating-multiple-linked-access-codes: low-level-apis/smart-locks/access-codes/creating-and-updating-multiple-linked-access-codes.md
  capability-guides/smart-locks/access-codes/deleting-access-codes: low-level-apis/smart-locks/access-codes/deleting-access-codes.md
  capability-guides/smart-locks/access-codes/lifecycle-of-access-codes: low-level-apis/smart-locks/access-codes/lifecycle-of-access-codes.md
  capability-guides/smart-locks/access-codes/migrating-existing-access-codes: low-level-apis/smart-locks/access-codes/migrating-existing-access-codes.md
  capability-guides/smart-locks/access-codes/modifying-access-codes: low-level-apis/smart-locks/access-codes/modifying-access-codes.md
  capability-guides/smart-locks/access-codes/retrieving-access-codes: low-level-apis/smart-locks/access-codes/retrieving-access-codes.md
  capability-guides/smart-locks/access-codes/troubleshooting-access-code-issues: low-level-apis/smart-locks/access-codes/troubleshooting-access-code-issues.md
  capability-guides/smart-locks/access-codes: low-level-apis/smart-locks/access-codes/README.md
  capability-guides/smart-locks/lock-and-unlock: low-level-apis/smart-locks/lock-and-unlock.md
  capability-guides/smart-locks: low-level-apis/smart-locks/README.md

  capability-guides/access-systems/connect-an-acs-to-seam/access-control-system-resources: low-level-apis/access-systems/connect-an-acs-to-seam/access-control-system-resources.md
  capability-guides/access-systems/connect-an-acs-to-seam/retrieving-acs-system-details: low-level-apis/access-systems/connect-an-acs-to-seam/retrieving-acs-system-details.md
  capability-guides/access-systems/connect-an-acs-to-seam/understanding-access-control-system-differences: low-level-apis/access-systems/connect-an-acs-to-seam/understanding-access-control-system-differences.md
  capability-guides/access-systems/user-management: low-level-apis/access-systems/user-management.md
  capability-guides/access-systems/working-with-card-encoders-and-scanners/creating-and-encoding-card-based-credentials: low-level-apis/access-systems/working-with-card-encoders-and-scanners/creating-and-encoding-card-based-credentials.md
  capability-guides/access-systems/working-with-card-encoders-and-scanners: low-level-apis/access-systems/working-with-card-encoders-and-scanners/README.md
  capability-guides/access-systems: low-level-apis/access-systems/README.md
  capability-guides/smart-locks/access-codes/creating-access-codes: low-level-apis/smart-locks/access-codes/creating-access-codes/README.md
  capability-guides/smart-locks/access-codes/offline-access-codes: low-level-apis/smart-locks/access-codes/offline-access-codes.md
  capability-guides/smart-locks/get-started-with-smartlocks-api: low-level-apis/smart-locks/get-started-with-smartlocks-api.md
  low-level-apis/access-codes: low-level-apis/smart-locks/access-codes/README.md
  low-level-apis/managing-credentials: low-level-apis/access-systems/managing-credentials.md
  use-cases/granting-access/access-grants: use-cases/granting-access/README.md
