/* eslint-disable no-console */
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import type { Blueprint } from '@seamapi/blueprint'

import { stripConceptLinks } from './concept-links.js'

/**
 * Generate event documentation for the API reference.
 *
 * Events are webhook payloads, not endpoints, so they have no OpenAPI
 * representation and were dropped when the API reference moved to
 * OpenAPI-generated pages. This module restores them from `blueprint.events`
 * (which the pipeline already builds but never reads) so they stay in sync with
 * `@seamapi/types` on every `npm run generate:mintlify`. It produces:
 *
 *   1. A dedicated `events.mdx` page per resource that emits events, each event
 *      documented with an example webhook payload and its properties. A
 *      standalone page (rather than a section on the object page) renders full
 *      width instead of squeezed into the object page's two-column layout, and
 *      gives each event a stable, linkable heading anchor.
 *   2. The full `event_type` enum on the Event object page.
 *
 * `update-nav.ts` wires the generated pages into the sidebar next to their
 * object page. Link canonicalization (Phase G) runs afterward so `docs.seam.co`
 * links in event descriptions become canonical relative paths.
 */

// Sentinel markers previously delimited an events section embedded in the
// object pages. They are matched (never emitted) only to strip that section
// from object pages generated by earlier versions of this module.
const EVENTS_START = '{/* SEAM-GENERATED-EVENTS:START */}'
const EVENTS_END = '{/* SEAM-GENERATED-EVENTS:END */}'

// Route path of the Event object page itself. Events do not emit events, so
// this path never appears in `blueprint.events`; it is handled separately to
// receive the full `event_type` enum.
const EVENT_OBJECT_ROUTE = '/events'

type EventResource = Blueprint['events'][number]
type EventProperty = EventResource['properties'][number]

/**
 * Map a blueprint property format to the type label used across the API object
 * pages (e.g. `id` -> `String (UUID)`, `enum` -> `Enum (String)`). Mirrors
 * `formatPropertyType` in generate.ts so event properties read the same as the
 * resource properties above them.
 */
function formatType(prop: EventProperty): string {
  switch (prop.format) {
    case 'id':
      return 'String (UUID)'
    case 'datetime':
      return 'String (ISO 8601)'
    case 'enum':
      return 'Enum (String)'
    case 'list':
      return 'Array'
    case 'boolean':
      return 'Boolean'
    case 'string':
      return 'String'
    case 'object':
    case 'record':
      return 'Object'
    default:
      return (prop as { jsonType?: string }).jsonType ?? 'String'
  }
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces)
  return text
    .split('\n')
    .map((line) => (line.trim() ? pad + line : line))
    .join('\n')
}

function hasEnumValues(
  prop: EventProperty,
): prop is EventProperty & { values: Array<{ name: string }> } {
  return (
    'values' in prop && Array.isArray((prop as { values?: unknown }).values)
  )
}

/**
 * Object-format properties (e.g. the `from`/`to` of a `*.*_changed` event)
 * carry their own typed `properties` array. Free-form records
 * (`*_custom_metadata`) have an empty array; those still render as `{}`.
 */
function hasNestedProperties(
  prop: EventProperty,
): prop is EventProperty & { properties: EventProperty[] } {
  return (
    'properties' in prop &&
    Array.isArray((prop as { properties?: unknown }).properties) &&
    (prop as { properties: unknown[] }).properties.length > 0
  )
}

// Illustrative values for well-known fields that the type system types as
// plain strings, so their `from`/`to` payloads read realistically instead of
// showing `""`. `*_at` string fields are handled as datetimes below.
const SAMPLE_STRING_VALUES: Record<string, string> = {
  code: '1234',
  name: 'My Access Code',
}

/**
 * Build an illustrative sample value for an event property from its format.
 * Values are fixed (never random) so generated payloads are stable across
 * runs; this mirrors the value conventions in load-data.ts.
 */
function sampleValue(prop: EventProperty): unknown {
  if (hasEnumValues(prop) && prop.values.length > 0) {
    return prop.values[0]?.name ?? ''
  }
  switch (prop.format) {
    case 'id':
      return '00000000-0000-0000-0000-000000000000'
    case 'datetime':
      return '2025-01-01T00:00:00.000Z'
    case 'boolean':
      return true
    case 'number':
      return 0
    case 'list':
      return []
    case 'object':
    case 'record': {
      // Typed objects (a `*_changed` event's `from`/`to`) expose their own
      // `properties`; recurse to show their shape. Free-form records have none
      // and stay `{}`.
      if (!hasNestedProperties(prop)) return {}
      const nested: Record<string, unknown> = {}
      for (const child of prop.properties) {
        if (child.isUndocumented) continue
        nested[child.name] = sampleValue(child)
      }
      return nested
    }
    case 'string':
      // Some datetime fields (e.g. a time frame's `starts_at`/`ends_at`) are
      // typed as plain strings; render them like the datetime fields above.
      if (/_at$/.test(prop.name)) return '2025-01-01T00:00:00.000Z'
      return SAMPLE_STRING_VALUES[prop.name] ?? ''
    default:
      return null
  }
}

/**
 * Synthesize an example webhook payload for an event so readers can see its
 * shape without triggering the event. `event_type` gets the concrete type and
 * `event_description` echoes the event's description (matching the real
 * payload); every other field gets a type-appropriate placeholder.
 */
function buildEventSample(event: EventResource): Record<string, unknown> {
  const sample: Record<string, unknown> = {}
  for (const prop of event.properties) {
    if (prop.isUndocumented) continue
    if (prop.name === 'event_type') {
      sample[prop.name] = event.eventType
    } else if (prop.name === 'event_description') {
      sample[prop.name] = event.description.trim()
    } else {
      sample[prop.name] = sampleValue(prop)
    }
  }
  return sample
}

/** Render an event's example payload as a JSON code block. */
function renderEventSample(event: EventResource): string {
  const json = JSON.stringify(buildEventSample(event), null, 2)
  return ['```json Example webhook payload', json, '```'].join('\n')
}

/** Render a single event property as a Mintlify `<ResponseField>`. */
function renderEventProperty(prop: EventProperty): string {
  const body: string[] = []

  // `event_type` is a single-value enum: show the concrete value.
  if (
    prop.name === 'event_type' &&
    hasEnumValues(prop) &&
    prop.values.length === 1 &&
    prop.values[0] != null
  ) {
    body.push(`Value: \`${prop.values[0].name}\``)
  } else {
    const description = stripConceptLinks((prop.description ?? '').trim())
    body.push(description || `The ${prop.name.replace(/_/g, ' ')}.`)

    if (hasEnumValues(prop) && prop.values.length > 0) {
      const values = prop.values.map((value) => `\`${value.name}\``).join(', ')
      body.push('', `Possible values: ${values}`)
    }
  }

  // Typed objects (a `*_changed` event's `from`/`to`) document their child
  // fields in a nested `<Expandable>`, matching the object pages.
  if (hasNestedProperties(prop)) {
    const children = prop.properties
      .filter((child) => !child.isUndocumented)
      .map((child) => indent(renderEventProperty(child), 4))
    if (children.length > 0) {
      body.push(
        '',
        '<Expandable title="properties">',
        ...children,
        '</Expandable>',
      )
    }
  }

  return [
    `<ResponseField name="${prop.name}" type="${formatType(prop)}">`,
    indent(body.join('\n'), 2),
    '</ResponseField>',
  ].join('\n')
}

/**
 * Render one event: its type and description, an example payload showing its
 * shape, then a collapsible `<Accordion>` of its properties. Mintlify strips
 * raw `<details>` elements, so the collapsible uses the native `<Accordion>`.
 */
function renderEvent(event: EventResource): string {
  const properties = event.properties
    .filter((prop) => !prop.isUndocumented)
    .map(renderEventProperty)
    .join('\n\n')

  return [
    `## \`${event.eventType}\``,
    '',
    stripConceptLinks(event.description.trim()),
    '',
    renderEventSample(event),
    '',
    '<Accordion title="Properties">',
    '',
    properties,
    '',
    '</Accordion>',
  ].join('\n')
}

/**
 * Derive the events page title from the sibling object page's title
 * (`The Access Grant Object` -> `Access Grant Events`), falling back to a
 * humanized route path when the object title is missing or unexpected.
 */
function deriveEventsTitle(
  objectContent: string | null,
  routePath: string,
): string {
  const match = objectContent?.match(/^title:\s*['"]?(.+?)['"]?\s*$/m)
  const objectTitle = match?.[1]
  const noun = objectTitle
    ?.replace(/^The\s+/, '')
    .replace(/\s+Object$/, '')
    .trim()
  if (noun) return `${noun} Events`

  const humanized = routePath
    .slice(1)
    .split('/')
    .map((seg) =>
      seg
        .split('_')
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' '),
    )
    .join(' ')
  return `${humanized} Events`
}

/** Render the full standalone events page (frontmatter + one section per event). */
function renderEventsPage(events: EventResource[], title: string): string {
  const description = `Webhook events that Seam emits for the ${title.replace(/\s+Events$/, '')} resource, with example payloads and properties.`
  const frontmatter = [
    '---',
    `title: '${title.replace(/'/g, "\\'")}'`,
    `description: '${description.replace(/'/g, "\\'")}'`,
    '---',
  ].join('\n')
  const body = events.map(renderEvent).join('\n\n')
  return `${frontmatter}\n\n${body}\n`
}

/**
 * Remove an events section embedded in an object page by an earlier version of
 * this module (delimited by the sentinel markers). Returns the cleaned content,
 * or null when there is nothing to strip.
 */
function stripEmbeddedEventsSection(content: string): string | null {
  const startIdx = content.indexOf(EVENTS_START)
  if (startIdx === -1) return null
  const endIdx = content.indexOf(EVENTS_END, startIdx)
  if (endIdx === -1) return null
  const after = endIdx + EVENTS_END.length
  const cleaned = `${content.slice(0, startIdx).replace(/\s+$/, '')}\n${content.slice(after).replace(/^\s+/, '\n')}`
  return cleaned.replace(/\n{3,}/g, '\n\n')
}

/**
 * Replace the `event_type` ResponseField on the Event object page with one that
 * lists every event type as enum values. Idempotent: matches the field whether
 * or not it already carries the enum block.
 */
function injectEventTypeEnum(content: string, eventTypes: string[]): string {
  const field = [
    '<ResponseField name="event_type" type="Enum (String)">',
    '  The event type.',
    '',
    '  <Accordion title="Enum values">',
    ...eventTypes.map((type) => `    - \`${type}\``),
    '  </Accordion>',
    '</ResponseField>',
  ].join('\n')

  return content.replace(
    /<ResponseField name="event_type"[^>]*>[\s\S]*?<\/ResponseField>/,
    field,
  )
}

/** Group events by the route path of the resource that emits them. */
function groupEventsByRoutePath(
  events: EventResource[],
): Map<string, EventResource[]> {
  const byRoute = new Map<string, EventResource[]>()
  for (const event of events) {
    const group = byRoute.get(event.routePath) ?? []
    group.push(event)
    byRoute.set(event.routePath, group)
  }
  return byRoute
}

async function readFileOrNull(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8')
  } catch {
    return null
  }
}

/**
 * Generate the per-resource `events.mdx` pages and the Event object page enum.
 * Returns the route paths that received an events page (e.g. `/access_grants`)
 * so the caller can wire them into the navigation.
 */
export async function updateEventPages(
  blueprint: Blueprint,
  docsDir: string,
): Promise<string[]> {
  const events = (blueprint.events ?? []).filter(
    (event) => !event.isUndocumented,
  )
  const eventPageRoutes: string[] = []

  // 1. A dedicated events page per resource, alongside its object page.
  for (const [routePath, routeEvents] of groupEventsByRoutePath(events)) {
    const resourceDir = join(docsDir, 'api', routePath.slice(1))
    const objectContent = await readFileOrNull(join(resourceDir, 'object.mdx'))
    if (objectContent == null) {
      // Some event route paths have no object page (e.g.
      // /user_identities/enrollment_automations). Skip until a page exists.
      console.log(`  No object page for events on ${routePath}, skipping`)
      continue
    }

    // Clean up any events section embedded in the object page by an earlier
    // version of this module (events now live on their own page).
    const stripped = stripEmbeddedEventsSection(objectContent)
    if (stripped != null) {
      await writeFile(join(resourceDir, 'object.mdx'), stripped)
    }

    const title = deriveEventsTitle(objectContent, routePath)
    await writeFile(
      join(resourceDir, 'events.mdx'),
      renderEventsPage(routeEvents, title),
    )
    eventPageRoutes.push(routePath)
  }

  // 2. Full `event_type` enum on the Event object page.
  const eventTypes = [...new Set(events.map((event) => event.eventType))]
  const eventObjectPath = join(
    docsDir,
    'api',
    EVENT_OBJECT_ROUTE.slice(1),
    'object.mdx',
  )
  const eventObjectContent = await readFileOrNull(eventObjectPath)
  if (eventObjectContent == null) {
    console.log(`  No Event object page at ${eventObjectPath}, skipping enum`)
  } else {
    const next = injectEventTypeEnum(eventObjectContent, eventTypes)
    if (next !== eventObjectContent) await writeFile(eventObjectPath, next)
  }

  return eventPageRoutes
}
