/* eslint-disable no-console */
import { readdir, readFile } from 'node:fs/promises'
import { join } from 'node:path'

import { type Blueprint, createBlueprint } from '@seamapi/blueprint'
import * as types from '@seamapi/types/connect'
// @ts-expect-error js-yaml has no type declarations
import jsYaml from 'js-yaml'

import { formatCode } from '../codegen/lib/format-code.js'

const yamlParse = (content: string): any => jsYaml.load(content)

interface PathMetadataEntry {
  title: string
  description?: string
  overview?: string
  alpha?: string
}

export type PathMetadata = Record<string, PathMetadataEntry>

/**
 * Load all YAML arrays from a directory, concatenating them into a flat array.
 * Replicates what @metalsmith/metadata does for directory sources.
 */
async function loadYamlArrayDir(dir: string): Promise<unknown[]> {
  const files = await readdir(dir)
  const arrays = await Promise.all(
    files
      .filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
      .sort()
      .map(async (f) => {
        const content = await readFile(join(dir, f), 'utf8')
        return yamlParse(content) as unknown[]
      }),
  )
  return arrays.flat()
}

/**
 * Load path metadata from paths.yaml.
 */
async function loadPathMetadata(filepath: string): Promise<PathMetadata> {
  const content = await readFile(filepath, 'utf8')
  return yamlParse(content) as PathMetadata
}

interface DiscriminatorConfig {
  resourceType: string
  property: string
}

const autoSampleDiscriminators: DiscriminatorConfig[] = [
  { resourceType: 'access_method', property: 'mode' },
]

function generateDefaultValue(propSchema: any): unknown {
  if (propSchema.enum) return propSchema.enum[0]
  switch (propSchema.type) {
    case 'string':
      if (propSchema.format === 'uuid')
        return '00000000-0000-0000-0000-000000000000'
      if (propSchema.format === 'date-time') return '2025-01-01T00:00:00.000Z'
      if (propSchema.format === 'uri') return 'https://example.com'
      return ''
    case 'boolean':
      return false
    case 'array':
      return []
    case 'object':
      return {}
    case 'number':
    case 'integer':
      return 0
    default:
      return null
  }
}

function humanize(value: string): string {
  return value
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function generateMissingSamples(existingSamples: any[]): any[] {
  const openapi = (types as any).openapi
  const schemas = openapi?.components?.schemas
  if (schemas == null) return []

  const generated: any[] = []

  for (const { resourceType, property } of autoSampleDiscriminators) {
    const schema = schemas[resourceType]
    if (schema?.properties?.[property]?.enum == null) continue

    const enumValues: string[] = schema.properties[property].enum
    const coveredValues = new Set(
      existingSamples
        .filter((s: any) => s.resource_type === resourceType)
        .map((s: any) => s.properties?.[property])
        .filter(Boolean),
    )

    const requiredFields: string[] = schema.required ?? []
    const allProperties: Record<string, any> = schema.properties ?? {}

    for (const value of enumValues) {
      if (coveredValues.has(value)) continue

      const properties: Record<string, unknown> = {}
      for (const field of requiredFields) {
        const propSchema = allProperties[field]
        if (propSchema == null) continue
        properties[field] =
          field === property ? value : generateDefaultValue(propSchema)
      }
      properties[property] = value

      generated.push({
        title: `${humanize(value)} ${humanize(resourceType)}`,
        description: `A ${value.replace(/_/g, ' ')} ${resourceType.replace(/_/g, ' ')} resource.`,
        resource_type: resourceType,
        properties,
      })

      console.log(
        `Auto-generated resource sample for ${resourceType} ${property}=${value}`,
      )
    }
  }

  return generated
}

/**
 * Create a Blueprint with code samples from @seamapi/types and YAML definitions.
 */
export async function loadBlueprint(
  skipCodeFormat: boolean,
): Promise<{ blueprint: Blueprint; pathMetadata: PathMetadata }> {
  const dataDir = join(import.meta.dirname, '..', 'codegen', 'data')

  const [codeSampleDefinitions, resourceSampleDefinitions, pathMetadata] =
    await Promise.all([
      loadYamlArrayDir(join(dataDir, 'code-sample-definitions')),
      loadYamlArrayDir(join(dataDir, 'resource-sample-definitions')),
      loadPathMetadata(join(dataDir, 'paths.yaml')),
    ])

  const autoGenerated = generateMissingSamples(
    resourceSampleDefinitions as any[],
  )
  const allResourceSamples = [...resourceSampleDefinitions, ...autoGenerated]

  const typesModule = {
    ...types,
    codeSampleDefinitions,
    resourceSampleDefinitions: allResourceSamples,
  }

  const blueprint = await createBlueprint(
    typesModule as any,
    skipCodeFormat ? {} : { formatCode },
  )

  return { blueprint, pathMetadata }
}

export function getRawOpenApiSpec(): any {
  return JSON.parse(JSON.stringify(types.openapi))
}
